// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "../RequestId";

/**
 * Progress while the app-server reads a legacy rollout for `thread/resume`.
 */
export type ThreadResumeProgressNotification = { requestId: RequestId, threadId: string,
/**
 * Percentage of the rollout decoded so far, from 0 to 100.
 */
progress: number, };
